[workspace]
resolver = "2"
members = ["apps/desktop", "spikes/spike-common", "spikes/spike1-net", "spikes/spike2-screen", "spikes/spike3-ghost", "spikes/spike4-captura", "apps/instalador"]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-or-later"

[profile.release]
opt-level = 3
lto = "thin"
